### ISSUE TITLE
Error on rcdimple when deploying to shinyapps.io

### ISSUE THREAD

**Issue by kilimba** [rstudio/shinyapps#143] opened 2015-04-22 09:20 UTC
Dear all, am newish to R and Shiny and have recently created a Shiny application which I would like to deploy on shinyapps.io. However I keep getting an error which seems to be linked with the rcdimple library (but I don't know enough to be sure). The details, including the code are in http://stackoverflow.com/questions/29745524/error-on-rcdimple-when-deploying-to-shinyapps-io

Any help greatly appreciated.

Tumaini

**Comment by kippandrew** [comment] 2015-04-22 13:21
I suspect the problem is with the rcdimple package.
Can you send long the output for: 

`packageDescription('rcdimple')`

As well as:

`shinyapps::appDependencies()`

**Comment by kilimba** [comment] 2015-04-23 08:43
Hello Kippandrew, as requested:

> packageDescription('rcdimple')
Package: rcdimple
Title: Dimple htmlwidget
Version: 0.1
Authors@R: c( person("John", "Kiernander", role = c("aut", "cph"), comment = "dimple.js
          library in htmlwidgets/lib, https://github.com/PMSI-AlignAlytics/dimple"),
          person("Mike", "Bostock", role = c("aut", "cph"), comment = "d3.js library in
          htmlwidgets/lib, http://d3js.org"), person("Jeremy", "Stucki", role = c("aut",
          "cph"), comment = "d3-grid library in htmlwidgets/lib,
          http://github.com/cpettitt/dagre-d3"), person("Kenton", "Russell", role = c("aut",
          "cre"), comment = "R interface", email = "kent.russell@timelyportfolio.com"),
          person("Ramnath", "Vaidyanathan", role = c("aut","ctb"), comment = "rCharts common
          interace functions", email = "ramnath.vaidya@gmail.com") )
Maintainer: Kenton Russell <kent.russell@timelyportfolio.com>
Description: Provides easy access to the dimple d3.js plotting library in the form of an
          htmlwidget.
Depends: R (>= 3.1.2)
License: MIT + file LICENSE
LazyData: true
Suggests: knitr, testthat
VignetteBuilder: knitr
RemoteType: github
RemoteHost: api.github.com
RemoteRepo: rcdimple
RemoteUsername: timelyportfolio
RemoteRef: master
RemoteSha: 6c721799271903d80f3f00df4192f3183b41ca25
GithubRepo: rcdimple
GithubUsername: timelyportfolio
GithubRef: master
GithubSHA1: 6c721799271903d80f3f00df4192f3183b41ca25
Author: John Kiernander [aut, cph] (dimple.js library in htmlwidgets/lib,
          https://github.com/PMSI-AlignAlytics/dimple), Mike Bostock [aut, cph] (d3.js
          library in htmlwidgets/lib, http://d3js.org), Jeremy Stucki [aut, cph] (d3-grid
          library in htmlwidgets/lib, http://github.com/cpettitt/dagre-d3), Kenton Russell
          [aut, cre] (R interface), Ramnath Vaidyanathan [aut, ctb] (rCharts common interace
          functions)
Built: R 3.1.2; ; 2015-03-23 20:42:09 UTC; windows

-- File: C:/Users/Tee/Documents/R/win-library/3.1/rcdimple/Meta/package.rds 

And:

> shinyapps::appDependencies()
          package  version
1           shiny   0.11.1
2  shinydashboard    0.3.0
3       htmltools    0.2.6
4     htmlwidgets    0.3.2
5        rcdimple      0.1
6            curl      0.5
7            plyr    1.8.1
8         rCharts    0.4.5
9           ggvis    0.4.1
10       reshape2    1.4.1
11          tools    3.1.3
12          utils    3.1.3
13         httpuv    1.3.2
14           mime      0.3
15        RJSONIO    1.3-0
16         xtable    1.7-4
17         digest    0.6.8
18             R6    2.0.1
19        methods    3.1.3
20           Rcpp   0.11.5
21           yaml   2.1.13
22        lattice  0.20-30
23          RCurl 1.95-4.5
24        whisker    0.3-2
25           grid    3.1.3
26      grDevices    3.1.3
27       graphics    3.1.3
28          stats    3.1.3
29         bitops    1.0-6
30     assertthat      0.1
31       jsonlite   0.9.15
32       magrittr      1.5
33          dplyr    0.4.1
34       lazyeval   0.1.10
35            DBI    0.3.1
36             BH 1.55.0-3
37        stringr    0.6.2

Sorry am not sure how to format code in here :-(

Thanks

**Comment by kippandrew** [comment] 2015-04-23 13:46
As I suspected the `rcdimple` package depends on `htmlwidgets` but does not list it as a dependency in its DESCRIPTION file. This is likely an oversight on the package author's part. You could reach out to the package author, or open a PR for the rcdimple package to resolve the issue.

**Comment by kippandrew** [comment] 2015-04-28 20:09
I see you PR was merged. Did fixing rcdimple resolve this issue?

**Comment by kilimba** [comment] 2015-04-29 21:50
Yes thanks that fixed the issue, thanks for the help :)

**Closed** 2015-06-03 14:30 UTC
